webtalk_init -webtalk_dir D:/code/verilog/FPGA_Project/ceres/ceres.sim/sim_1/behav/xsim/xsim.dir/datapath_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  7 17:00:49 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ef703992-f4fd-48c9-8fa8-4e28aeb1d499" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "17ce457bd4784e16a7a7b822779d48e2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "66" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1797 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 601752272 -regid "" -xml D:/code/verilog/FPGA_Project/ceres/ceres.sim/sim_1/behav/xsim/xsim.dir/datapath_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/code/verilog/FPGA_Project/ceres/ceres.sim/sim_1/behav/xsim/xsim.dir/datapath_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/code/verilog/FPGA_Project/ceres/ceres.sim/sim_1/behav/xsim/xsim.dir/datapath_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
